### ISSUE TITLE
Please include support of SSLv3 'cause it is necessary for sending via Exchange

### ISSUE THREAD

**Issue by VladimirDe** [mludvig/smtp-cli#15]

**Comment by mludvig** [comment]
Hi, SSLv3 has been deprecated for years! I’d be surprised if any well maintained servers still used it. 

Having said that the `smtp-cli` cryptography support depends on the system libraries - and all recent systems have SSLv3 disabled. 

I’m afraid I can’t help. If your server still requires SSLv3 it’s time to upgrade it to enable at least TLSv1 or newer.
