### ISSUE TITLE
SMTP Server Error response: [503 bad sequence of commands] when following example.

### ISSUE THREAD

**Issue by kitatek** [mludvig/smtp-cli#24]
Hello,

Seems this doesn't work out of the box with this provider, even with tested correct user and password.

Tested both on CentOS 6.10 and Ubuntu 20.04 with dependencies installed (including the missing dns dependency of Ubuntu). 

Any idea what would be wrong in the command ?
How to debug the exchanges between client and server ?

```
$ smtp-cli --verbose --host smtp.mxhichina.com --enable-auth --user 'user@example.com' --password 'whatever' --from 'user@example.com' --to 'receiver@example.com' --subject 'test use smtp-cli' --body-plain=/etc/lsb-release
Connection from 10.1.2.3:48402 to 59.82.44.168:25
[220] 'smtp.aliyun-inc.com MX AliMail Server'
> HELO localhost
[250] 'Ok'
> MAIL FROM:<user@example.com>
[503] 'bad sequence of commands'
MAIL FROM <user@example.com> failed: '503 bad sequence of commands'
> QUIT
[221] 'Bye'
```

Thanks.

**Comment by mludvig** [comment]
That’s interesting. Can you try with `--force-ehlo`?

**Comment by kitatek** [comment]
Works now ! Thank you.

**Comment by mludvig** [comment]
Good to hear that :)
