### ISSUE TITLE
socket timeout fails on older versions of IO::Socket::SSL

### ISSUE THREAD

**Issue by teleshoes** [mludvig/smtp-cli#7]
i need to remove the timeout to get this to work on a Nokia N9.
IO::Socket 1.33 {libio-socket-ssl-perl_1.33-1+squeeze1_all.deb}
Net::SSLeay 1.36 {libnet-ssleay-perl_1.36-1_armel.deb}

a good workaround, i think, would be to add a CLI option to remove the Timeout => 5 from the socket {--no-socket-timeout}. what do you think of this approach?

without removing the timeout, i get this:
SSL/TLS: SSL connect attempt failed with unknown error error:00000000:lib(0):func(0):reason(0)

with the timeout removed from the script, it works like a charm. note that the errors happen instantly, for whatever reason, not after 5 seconds, and with the timeout removed, the socket connects in a few milliseconds.

**Comment by mludvig** [comment]
Hi Elliot

Thanks for the report. This could well be a bug in one of the perl libraries - the current version of IO::Socket::SSL is 2.010 and the current version of Net::SSLeay is 1.68 - I suggest you test it with these first before implementing a workaround. Feel free to reopen the ticket if it still fails the up to date perl libs.

Michael

**Comment by teleshoes** [comment]
thanks for the response!
yea, this ticket is definitely not a bug in smtp-cli. the point of this Issue is to point out an incompatibility with a particular platform, due to old libs on that platform. {it runs perfectly fine on my debian boxes, it just doesnt run on my Nokia N9}

the platform in question is meego harmattan, and upgrading the libs is difficult for a variety of reasons. the perl on the N9 is an ancient copy of perl 5.10, and i cant seem to get cpan to compile the libs.

smtp-cli works GREAT on the N9 as-is, but only if you remove the timeout. i use smtp-cli in my own cross-platform email client, and i was hoping to add smtp-cli as a dependency instead of maintaining a forked copy of it bundled with my client.
{your authorship and copyrights will be correctly presented according to the terms of the GPLv3}

**Comment by mludvig** [comment]
Hi

Yes I get what you're saying but really not very keen to work around bugs in such old libraries. If it was failing with something more recent or affecting more people then indeed I would be keen to merge it but to be honest I have never had this bugreport before so I assume it doesn't affect many people. 

On the other hand smtp-cli is doing what it's supposed to do and new versions are not being released very often so maintaining a forked version shouldn't be too difficult.

Sorry for the inconvenience!

Michal

**Comment by teleshoes** [comment]
yep, makes sense. will do, thanks
