### ISSUE TITLE
SMTP syntax errors

### ISSUE THREAD

**Issue by DerDakon** [mludvig/smtp-cli#9]
It's "MAIL FROM:<…>" and "RCPT TO:<…>", i.e. no spaces between colon and opening brace, see [RfC 5321](https://tools.ietf.org/html/rfc5321#page-20).

**Comment by mludvig** [comment]
Thanks for the report, you're indeed correct. Out of interest - what 
SMTP server rejects the space? I haven't had any other reports about that...

Michael

**Comment by DerDakon** [comment]
Qsmtp has a per-user setting to reject those as they are often a sign of spam bots.
